/**:
    ros__parameters:
      video_device: "/dev/urc/cam/logitech_09"
      framerate: 15.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      av_device_format: "YUV422P"
      image_width: 320
      image_height: 240
      camera_name: "test_camera"
      camera_info_url: "./logitech_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1